from pathlib import Path

p=Path('appsrc/public/index.html')
s=p.read_text(encoding='utf-8')

old_css=""".routeBanner{max-width:1424px;margin:12px auto 28px;background:linear-gradient(110deg,var(--navy) 0,var(--navy) 30%,#f8fcf4 30%,#f8fcf4 67%,#e6f4dc 100%);border-radius:12px;overflow:hidden;display:grid;grid-template-columns:360px 1fr 360px;min-height:120px;box-shadow:var(--shadow)}.rbTitle{color:#fff;padding:24px 26px;display:flex;gap:17px;align-items:center}.rbTitle .truck{font-size:50px}.rbTitle b{font-size:22px}.rbTitle b span{color:var(--orange)}.rbTitle small{display:block;font-size:15px;margin-top:2px}.rbFeatures{display:grid;grid-template-columns:repeat(3,1fr);align-items:center;gap:12px;padding:15px 24px}.rbFeatures b{font-size:11px;display:block}.rbFeatures small{font-size:10px;color:#40516b;line-height:1.3}.van{background:linear-gradient(90deg,rgba(230,244,220,.1),rgba(230,244,220,.35)),url('https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=80') center/cover}.benefits"""
new_css=""".routeBanner{max-width:1424px;margin:18px auto 30px;background:#fff;border:1px solid #dfe7ee;border-radius:18px;overflow:hidden;display:grid;grid-template-columns:360px 1fr 315px;min-height:148px;box-shadow:0 12px 34px rgba(3,52,95,.12)}.rbTitle{color:#fff;padding:26px 28px;display:flex;gap:16px;align-items:center;background:linear-gradient(135deg,var(--navy2),var(--navy));position:relative}.rbTitle:after{content:'';position:absolute;right:-28px;top:0;width:56px;height:100%;background:var(--navy);clip-path:polygon(0 0,100% 50%,0 100%);z-index:2}.rbTitle .truck{width:58px;height:58px;border-radius:16px;background:#ffffff18;display:grid;place-items:center;font-size:34px;border:1px solid #ffffff26}.rbTitle b{font-size:22px;line-height:1.05;letter-spacing:-.3px}.rbTitle b span{color:var(--orange)}.rbTitle small{display:block;font-size:12px;margin-top:7px;color:#dbe7f1;font-weight:700}.rbFeatures{display:grid;grid-template-columns:repeat(3,1fr);align-items:stretch;gap:10px;padding:22px 24px 22px 40px;background:linear-gradient(90deg,#fff,#f8fbf5)}.rbFeature{border:1px solid #e3ebdf;border-radius:12px;padding:14px 13px;background:#fff;display:flex;gap:10px;align-items:flex-start}.rbFeature .fi{width:30px;height:30px;border-radius:9px;background:#edf8e7;color:#4b8b26;display:grid;place-items:center;font-size:15px;font-weight:950;flex:0 0 auto}.rbFeatures b{font-size:11px;display:block;color:var(--navy);margin-bottom:4px}.rbFeatures small{font-size:9.5px;color:#5a6b7d;line-height:1.4}.van{position:relative;background:linear-gradient(90deg,rgba(3,38,74,.05),rgba(3,38,74,.0)),url('https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=86') center/cover}.van:after{content:'RutaFV';position:absolute;right:16px;bottom:14px;background:#06345fe6;color:#fff;border-radius:999px;padding:6px 11px;font-size:10px;font-weight:900;border:1px solid #ffffff40}.benefits"""
if old_css not in s:
    raise SystemExit('No se encontró CSS del banner RutaFV')
s=s.replace(old_css,new_css)

old_html="""<section class=\"routeBanner\"><div class=\"rbTitle\"><div class=\"truck\">🚚</div><div><b>Entrega con <span>RutaFV</span></b><small>En toda Fuerteventura</small></div></div><div class=\"rbFeatures\"><div><b>⌖ Cobertura total</b><small>Entregamos en todos los municipios de la isla</small></div><div><b>▣ Servicio profesional</b><small>Transporte seguro y descarga en obra o domicilio</small></div><div><b>☼ Seguimiento en tiempo real</b><small>Sabes dónde está tu pedido en todo momento</small></div></div><div class=\"van\"></div></section>"""
new_html="""<section class=\"routeBanner\"><div class=\"rbTitle\"><div class=\"truck\">🚚</div><div><b>Entrega profesional<br>con <span>RutaFV</span></b><small>Tu compra, entregada en cualquier punto de Fuerteventura</small></div></div><div class=\"rbFeatures\"><div class=\"rbFeature\"><span class=\"fi\">⌖</span><div><b>Cobertura insular</b><small>Servicio de entrega en todos los municipios de Fuerteventura.</small></div></div><div class=\"rbFeature\"><span class=\"fi\">✓</span><div><b>Transporte profesional</b><small>Mercancía gestionada con seguimiento y entrega coordinada.</small></div></div><div class=\"rbFeature\"><span class=\"fi\">↗</span><div><b>Seguimiento del pedido</b><small>Consulta el estado del reparto desde la preparación hasta la entrega.</small></div></div></div><div class=\"van\"></div></section>"""
if old_html not in s:
    raise SystemExit('No se encontró HTML del banner RutaFV')
s=s.replace(old_html,new_html)

s=s.replace("@media(max-width:1050px){.mainhead{grid-template-columns:220px 1fr auto}.headActions .fav{display:none}.mainhead{height:auto;padding-block:17px}.navin{overflow:auto;justify-content:flex-start}.cats{grid-template-columns:repeat(4,1fr)}.products{grid-template-columns:repeat(3,1fr)}.routeBanner{margin-inline:20px;grid-template-columns:300px 1fr}.van{display:none}.footerin{grid-template-columns:repeat(3,1fr)}}", "@media(max-width:1050px){.mainhead{grid-template-columns:220px 1fr auto}.headActions .fav{display:none}.mainhead{height:auto;padding-block:17px}.navin{overflow:auto;justify-content:flex-start}.cats{grid-template-columns:repeat(4,1fr)}.products{grid-template-columns:repeat(3,1fr)}.routeBanner{margin-inline:20px;grid-template-columns:300px 1fr}.van{display:none}.rbFeatures{padding-left:38px}.footerin{grid-template-columns:repeat(3,1fr)}}")
s=s.replace("@media(max-width:700px){.adminTop.show{display:flex;padding:9px 10px;font-size:0}.adminTop.show::first-letter{font-size:16px}.announce{font-size:10px;height:28px}.mainhead{grid-template-columns:1fr auto;padding:13px 14px;gap:12px}.logo{font-size:31px}.tagline{font-size:8px}.search{grid-column:1/-1;grid-row:2;height:44px}.headActions{gap:12px}.ha div:not(.badge){display:none}.ha .icon{font-size:23px}.hero{min-height:510px;background-position:63% center}.heroInner{padding:48px 23px}.hero h1{font-size:41px;max-width:430px}.hero p{font-size:15px;max-width:390px}.catsWrap{padding:8px 14px;margin-top:0}.cats{grid-template-columns:repeat(2,1fr)}.cat{min-height:72px}.section{padding:0 14px}.products{display:flex;overflow:auto;scroll-snap-type:x mandatory}.product{min-width:230px;scroll-snap-align:start}.routeBanner{margin:18px 14px;display:block;background:var(--navy)}.rbFeatures{background:#f8fcf4;grid-template-columns:1fr}.benefits", "@media(max-width:700px){.adminTop.show{display:flex;padding:9px 10px;font-size:0}.adminTop.show::first-letter{font-size:16px}.announce{font-size:10px;height:28px}.mainhead{grid-template-columns:1fr auto;padding:13px 14px;gap:12px}.logo{font-size:31px}.tagline{font-size:8px}.search{grid-column:1/-1;grid-row:2;height:44px}.headActions{gap:12px}.ha div:not(.badge){display:none}.ha .icon{font-size:23px}.hero{min-height:510px;background-position:63% center}.heroInner{padding:48px 23px}.hero h1{font-size:41px;max-width:430px}.hero p{font-size:15px;max-width:390px}.catsWrap{padding:8px 14px;margin-top:0}.cats{grid-template-columns:repeat(2,1fr)}.cat{min-height:72px}.section{padding:0 14px}.products{display:flex;overflow:auto;scroll-snap-type:x mandatory}.product{min-width:230px;scroll-snap-align:start}.routeBanner{margin:18px 14px;display:block}.rbTitle:after{display:none}.rbTitle{padding:22px}.rbFeatures{background:#f8fcf4;grid-template-columns:1fr;padding:14px}.rbFeature{padding:12px}.benefits")

s=s.replace('<!-- FVM_NAV_TABS_V1 -->','<!-- FVM_RUTAFV_BANNER_V2 -->\n<!-- FVM_NAV_TABS_V1 -->')
p.write_text(s,encoding='utf-8')
print('OK banner RutaFV V2 aplicado')
