from pathlib import Path

p=Path('appsrc/public/admin.html')
s=p.read_text(encoding='utf-8')

s=s.replace('.aiImage{border:1px solid var(--line);border-radius:9px;padding:7px;background:#f8fbfd;cursor:pointer}', '.aiImage{border:2px solid var(--line);border-radius:9px;padding:7px;background:#f8fbfd;cursor:pointer;position:relative;transition:.15s}.aiImage:hover{border-color:#9fc97f}.aiImage.selected{border-color:var(--lime);background:#eff9e8;box-shadow:0 0 0 3px #82c34126}.aiImage.selected:after{content:"✓ Seleccionada";position:absolute;right:7px;top:7px;background:var(--lime);color:#17320d;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:950}.imagePickCount{grid-column:1/-1;background:#edf6ff;border:1px solid #cfe0ef;border-radius:8px;padding:9px 11px;font-size:11px;font-weight:900;color:var(--navy)}.imagePickCount.ready{background:#edf8e7;border-color:#cfe7bf;color:#3f7421}')

old="""function renderSingleImages(){const box=$('imageSuggest');if(!box)return;const src=draft.sourceImages||[];const alt=draft.alternativeImages||[];const cards=(arr,kind)=>arr.map((im,j)=>'<div class=\"aiImage\" onclick=\"chooseSingleImage(\\''+kind+'\\','+j+')\"><img src=\"'+esc(im.url)+'\"><small>'+esc(kind==='source'?'Imagen de origen · revisar licencia':(im.license||'Imagen similar'))+'</small></div>').join('');box.innerHTML=(src.length?'<div class=\"imgGroupTitle\" style=\"grid-column:1/-1\">Imágenes reales de la ficha de origen</div>'+cards(src,'source'):'')+(alt.length?'<div class=\"imgGroupTitle\" style=\"grid-column:1/-1\">Alternativas más coincidentes</div>'+cards(alt,'similar'):'')+(!src.length&&!alt.length?'<div class=\"msg\">No se encontraron imágenes relacionadas. Puedes introducir una URL manualmente.</div>':'')}
function chooseSingleImage(kind,j){const im=(kind==='source'?draft.sourceImages:draft.alternativeImages)?.[j];if(!im)return;draft.image=im.url;draft.imageSource=im.source||'';draft.imageLicense=im.license||'';draft.imageAuthor=im.author||'';draft.images=[{...im,origin:kind}];$('image').value=im.url}
"""
new="""function renderSingleImages(){const box=$('imageSuggest');if(!box)return;const src=draft.sourceImages||[];const alt=draft.alternativeImages||[];draft.images=Array.isArray(draft.images)?draft.images:[];const selected=new Set(draft.images.map(x=>x.url));const cards=(arr,kind)=>arr.map((im,j)=>'<div class=\"aiImage '+(selected.has(im.url)?'selected':'')+'\" onclick=\"chooseSingleImage(\\''+kind+'\\','+j+')\"><img src=\"'+esc(im.url)+'\"><small>'+esc(kind==='source'?'Imagen de origen · revisar licencia':(im.license||'Imagen similar'))+'</small></div>').join('');const n=draft.images.length;box.innerHTML='<div class=\"imagePickCount '+(n>=3?'ready':'')+'\">'+n+' imágenes seleccionadas · mínimo 3 para guardar'+(n>=3?' ✓':'')+'</div>'+(src.length?'<div class=\"imgGroupTitle\" style=\"grid-column:1/-1\">Imágenes reales de la ficha de origen</div>'+cards(src,'source'):'')+(alt.length?'<div class=\"imgGroupTitle\" style=\"grid-column:1/-1\">Alternativas más coincidentes</div>'+cards(alt,'similar'):'')+(!src.length&&!alt.length?'<div class=\"msg\">No se encontraron imágenes relacionadas. Puedes introducir una URL manualmente.</div>':'');const btn=document.querySelector('[onclick=\"createProduct()\"]');if(btn){btn.disabled=n<3;btn.style.opacity=n<3?'.5':'1';btn.title=n<3?'Selecciona al menos 3 imágenes':''}}
function chooseSingleImage(kind,j){const im=(kind==='source'?draft.sourceImages:draft.alternativeImages)?.[j];if(!im)return;draft.images=Array.isArray(draft.images)?draft.images:[];const pos=draft.images.findIndex(x=>x.url===im.url);if(pos>=0){draft.images.splice(pos,1)}else{draft.images.push({...im,origin:kind})}const first=draft.images[0];draft.image=first?.url||'';draft.imageSource=first?.source||'';draft.imageLicense=first?.license||'';draft.imageAuthor=first?.author||'';$('image').value=draft.image;renderSingleImages()}
"""
if old not in s:
    raise SystemExit('No se encontró bloque renderSingleImages/chooseSingleImage')
s=s.replace(old,new)

s=s.replace("draft.images=draft.sourceImages||draft.images||[];draft.alternativeImages=[];renderSingleImages();", "draft.images=[];draft.alternativeImages=[];renderSingleImages();")

old2="async function createProduct(){try{const body={...draft,title:$('title').value,category:$('category').value,ref:$('ref').value,price:Number($('price').value)||0,sourcePrice:Number($('sourcePrice').value)||0,sourceProvider:$('sourceProvider')?.value||draft.sourceProvider||'',sourceRef:$('sourceRef')?.value||draft.sourceRef||'',sourceEan:$('sourceEan')?.value||draft.sourceEan||'',sourceUrl:$('sourceUrl')?.value||draft.sourceUrl||$('url').value.trim()||'',margin:Number($('margin').value)||0,addedValue:Number($('addedValue').value)||0,image:$('image').value,description:$('description').value,images:draft.images||[],featured:$('featured').checked,published:$('published').checked};if(!body.title.trim())throw Error('El producto necesita un título.');"
new2="async function createProduct(){try{const body={...draft,title:$('title').value,category:$('category').value,ref:$('ref').value,price:Number($('price').value)||0,sourcePrice:Number($('sourcePrice').value)||0,sourceProvider:$('sourceProvider')?.value||draft.sourceProvider||'',sourceRef:$('sourceRef')?.value||draft.sourceRef||'',sourceEan:$('sourceEan')?.value||draft.sourceEan||'',sourceUrl:$('sourceUrl')?.value||draft.sourceUrl||$('url').value.trim()||'',margin:Number($('margin').value)||0,addedValue:Number($('addedValue').value)||0,image:$('image').value,description:$('description').value,images:draft.images||[],featured:$('featured').checked,published:$('published').checked};if(!body.title.trim())throw Error('El producto necesita un título.');if((body.images||[]).length<3)throw Error('Selecciona al menos 3 imágenes haciendo clic sobre ellas antes de guardar.');"
if old2 not in s:
    raise SystemExit('No se encontró createProduct')
s=s.replace(old2,new2)

s=s.replace('<!-- FVM_IMAGE_MANAGER_V2 -->','<!-- FVM_IMAGE_MULTISELECT_V3 -->\n<!-- FVM_IMAGE_MANAGER_V2 -->')
p.write_text(s,encoding='utf-8')
print('OK multiselección de imágenes aplicada')
