from pathlib import Path

idx=Path('appsrc/public/index.html')
s=idx.read_text(encoding='utf-8')

old="""<div class=\"drawer\" id=\"cartDrawer\"><div class=\"shade\" onclick=\"closeCart()\"></div><aside class=\"cartPanel\"><button class=\"close\" onclick=\"closeCart()\">×</button><h2>Tu carrito</h2><div id=\"cartItems\"></div><div class=\"cartTotal\" id=\"cartTotal\">0,00 €</div><div class=\"field\"><label>Dirección de entrega</label><input id=\"orderAddress\" placeholder=\"Dirección completa\"></div><div class=\"field\"><label>Teléfono</label><input id=\"orderPhone\" placeholder=\"Teléfono de contacto\"></div><div class=\"field\"><label><input id=\"useRutaFV\" type=\"checkbox\" onchange=\"toggleRutaFV()\"> Entrega con RutaFV</label></div><div id=\"rutaFVQuoteBox\" class=\"msg\" style=\"display:none\"></div>"""
new="""<div class=\"drawer\" id=\"cartDrawer\"><div class=\"shade\" onclick=\"closeCart()\"></div><aside class=\"cartPanel\"><button class=\"close\" onclick=\"closeCart()\">×</button><h2>Tu carrito</h2><div id=\"cartItems\"></div><div class=\"cartTotal\" id=\"cartTotal\">0,00 €</div><div class=\"checkoutCustomer\"><h3>Datos del cliente y entrega</h3><div class=\"field\"><label>Nombre y apellidos / empresa</label><input id=\"orderName\" placeholder=\"Nombre completo o empresa\"></div><div class=\"field\"><label>Email</label><input id=\"orderEmail\" type=\"email\" placeholder=\"correo@ejemplo.com\"></div><div class=\"field\"><label>Teléfono</label><input id=\"orderPhone\" placeholder=\"Teléfono de contacto\"></div><div class=\"field\"><label>Dirección de entrega</label><input id=\"orderAddress\" placeholder=\"Calle, número, piso/puerta\"></div><div class=\"checkout2\"><div class=\"field\"><label>Municipio / localidad</label><input id=\"orderCity\" placeholder=\"Ej. Gran Tarajal\"></div><div class=\"field\"><label>Código postal</label><input id=\"orderPostalCode\" inputmode=\"numeric\" placeholder=\"35620\"></div></div><div class=\"field\"><label>Observaciones para la entrega</label><input id=\"orderNotes\" placeholder=\"Acceso, horario, referencia del lugar…\"></div></div><label class=\"rutaFVChoice\"><input id=\"useRutaFV\" type=\"checkbox\" onchange=\"toggleRutaFV()\"><span><b>Entrega con RutaFV</b><small>Calculamos el transporte y lo cobramos junto con la compra.</small></span></label><div id=\"rutaFVQuoteBox\" class=\"msg\" style=\"display:none\"></div>"""
if old not in s: raise SystemExit('checkout block not found')
s=s.replace(old,new)

s=s.replace('.routeQuote{background:#edf6ff;border:1px solid #cfe0ef;border-radius:9px;padding:10px;margin:8px 0}', '.routeQuote{background:#edf6ff;border:1px solid #cfe0ef;border-radius:9px;padding:10px;margin:8px 0}.checkoutCustomer{background:#f7f9fc;border:1px solid var(--line);border-radius:12px;padding:13px;margin:12px 0}.checkoutCustomer h3{font-size:14px;margin:0 0 9px}.checkout2{display:grid;grid-template-columns:1fr 120px;gap:8px}.rutaFVChoice{display:flex;align-items:flex-start;gap:10px;border:1px solid #cfe0ef;background:#f1f7fd;border-radius:10px;padding:12px;margin:10px 0;cursor:pointer}.rutaFVChoice input{width:18px;height:18px;margin-top:2px}.rutaFVChoice b{display:block;font-size:12px;color:var(--navy)}.rutaFVChoice small{display:block;font-size:10px;color:#52677d;margin-top:2px}@media(max-width:430px){.checkout2{grid-template-columns:1fr}}')

oldfn="""async function toggleRutaFV(){const box=document.getElementById('rutaFVQuoteBox');if(!useRutaFV.checked){rutaFVQuote=null;box.style.display='none';renderCart();return}if(!await requireLogin()){useRutaFV.checked=false;return}if(!orderAddress.value.trim()){box.style.display='block';box.textContent='Introduce primero la dirección de entrega.';useRutaFV.checked=false;return}box.style.display='block';box.className='routeQuote';box.textContent='Calculando transporte con RutaFV…';try{rutaFVQuote=await api('/api/rutafv/quote',{method:'POST',body:JSON.stringify({items:cart,address:orderAddress.value,phone:orderPhone.value})});const amount=Number(rutaFVQuote.amount??rutaFVQuote.total??0);box.textContent=`RutaFV · Transporte ${eur(amount)} · se cobrará junto con los productos`;renderCart()}catch(e){rutaFVQuote=null;useRutaFV.checked=false;box.textContent='No se pudo calcular RutaFV: '+e.message}}"""
newfn="""function deliveryCustomer(){return {name:(orderName?.value||session?.user?.name||'').trim(),email:(orderEmail?.value||session?.user?.email||'').trim(),phone:(orderPhone?.value||'').trim(),address:(orderAddress?.value||'').trim(),city:(orderCity?.value||'').trim(),postalCode:(orderPostalCode?.value||'').trim(),notes:(orderNotes?.value||'').trim()}}\nfunction validateDeliveryCustomer(){const c=deliveryCustomer();if(!c.name)return 'Introduce el nombre del cliente.';if(!c.email)return 'Introduce el email.';if(!c.phone)return 'Introduce el teléfono.';if(!c.address)return 'Introduce la dirección de entrega.';if(!c.city)return 'Introduce el municipio o localidad.';if(!c.postalCode)return 'Introduce el código postal.';return ''}\nasync function toggleRutaFV(){const box=document.getElementById('rutaFVQuoteBox');if(!useRutaFV.checked){rutaFVQuote=null;box.style.display='none';renderCart();return}if(!await requireLogin()){useRutaFV.checked=false;return}const err=validateDeliveryCustomer();if(err){box.style.display='block';box.className='routeQuote';box.textContent=err;useRutaFV.checked=false;return}const customer=deliveryCustomer();box.style.display='block';box.className='routeQuote';box.textContent='Calculando transporte con RutaFV…';try{rutaFVQuote=await api('/api/rutafv/quote',{method:'POST',body:JSON.stringify({items:cart,customer,address:customer.address,city:customer.city,postalCode:customer.postalCode,phone:customer.phone,notes:customer.notes})});const amount=Number(rutaFVQuote.amount??rutaFVQuote.total??0);box.textContent=`RutaFV · Transporte ${eur(amount)} · se cobrará junto con los productos`;renderCart()}catch(e){rutaFVQuote=null;box.textContent='RutaFV no respondió a tiempo. Puedes revisar los datos y volver a intentarlo.'}}"""
if oldfn not in s: raise SystemExit('toggleRutaFV block not found')
s=s.replace(oldfn,newfn)

s=s.replace("function logout(){session=null;localStorage.removeItem('fv_session');refreshAccount()}function refreshAccount(){", "function logout(){session=null;localStorage.removeItem('fv_session');refreshAccount()}function fillCheckoutCustomer(){if(!session?.user)return;const n=document.getElementById('orderName'),e=document.getElementById('orderEmail');if(n&&!n.value)n.value=session.user.name||'';if(e&&!e.value)e.value=session.user.email||''}function refreshAccount(){")
s=s.replace("if(logged){userInfo.textContent=`${session.user.name} · ${session.user.email}`}}", "if(logged){userInfo.textContent=`${session.user.name} · ${session.user.email}`;fillCheckoutCustomer()}}")

oldtr="""async function requireLogin(){if(session)return true;openAccount();authMsg.textContent='Inicia sesión para finalizar el pedido.';return false}async function placeTransfer(){if(!await requireLogin())return;try{const o=await api('/api/orders',{method:'POST',body:JSON.stringify({items:cart,address:orderAddress.value,phone:orderPhone.value,paymentMethod:'transfer',useRutaFV:!!useRutaFV?.checked,rutaFVQuote:rutaFVQuote||null})});cart=[];saveCart();renderCart();cartMsg.textContent='Pedido '+o.number+' creado correctamente. Pendiente de transferencia.'}catch(e){cartMsg.textContent=e.message}}\nasync function checkoutStripe(){if(!await requireLogin())return;try{const routeEl=document.getElementById('useRutaFV');const use=!!(routeEl&&routeEl.checked);if(use&&!rutaFVQuote){cartMsg.textContent='Calcula primero el transporte RutaFV.';return}const r=await api('/api/checkout/stripe',{method:'POST',body:JSON.stringify({items:cart,useRutaFV:use,rutaFVQuote:rutaFVQuote||null,address:orderAddress.value,phone:orderPhone.value})});location.href=r.url}catch(e){cartMsg.textContent=e.message}}"""
newtr="""async function requireLogin(){if(session)return true;openAccount();authMsg.textContent='Inicia sesión para finalizar el pedido.';return false}async function placeTransfer(){if(!await requireLogin())return;const err=validateDeliveryCustomer();if(err){cartMsg.textContent=err;return}try{const customer=deliveryCustomer();const o=await api('/api/orders',{method:'POST',body:JSON.stringify({items:cart,customer,address:customer.address,city:customer.city,postalCode:customer.postalCode,phone:customer.phone,notes:customer.notes,paymentMethod:'transfer',useRutaFV:!!useRutaFV?.checked,rutaFVQuote:rutaFVQuote||null})});cart=[];saveCart();renderCart();cartMsg.textContent='Pedido '+o.number+' creado correctamente. Pendiente de transferencia.'}catch(e){cartMsg.textContent=e.message}}\nasync function checkoutStripe(){if(!await requireLogin())return;const err=validateDeliveryCustomer();if(err){cartMsg.textContent=err;return}try{const customer=deliveryCustomer();const routeEl=document.getElementById('useRutaFV');const use=!!(routeEl&&routeEl.checked);if(use&&!rutaFVQuote){cartMsg.textContent='Calcula primero el transporte RutaFV.';return}const r=await api('/api/checkout/stripe',{method:'POST',body:JSON.stringify({items:cart,customer,useRutaFV:use,rutaFVQuote:rutaFVQuote||null,address:customer.address,city:customer.city,postalCode:customer.postalCode,phone:customer.phone,notes:customer.notes})});location.href=r.url}catch(e){cartMsg.textContent=e.message}}"""
if oldtr not in s: raise SystemExit('checkout functions block not found')
s=s.replace(oldtr,newtr)
idx.write_text(s,encoding='utf-8')

srv=Path('appsrc/server.js')
t=srv.read_text(encoding='utf-8')
t=t.replace("signal:AbortSignal.timeout(15000)","signal:AbortSignal.timeout(30000)")
oldroute="""app.post('/api/rutafv/quote',auth,async(req,res)=>{try{const d=read();const items=[];for(const x of req.body.items||[]){const p=d.products.find(y=>y.id===x.id);if(p)items.push({ref:p.ref,title:p.title,qty:Math.max(1,Number(x.qty)||1),weightKg:Number(p.weightKg||0),sourceProvider:p.sourceProvider||'',sourceUrl:p.sourceUrl||''})}const payload={clientCode:RUTAFV_CLIENT_CODE,customer:{name:req.user.name||'',email:req.user.email||'',phone:String(req.body.phone||'')},destination:String(req.body.address||''),items,orderSource:'FVMarket'};const q=await rutaFVRequest(RUTAFV_QUOTE_PATH,payload);res.json(q)}catch(e){res.status(503).json({error:e.message})}});"""
newroute="""app.post('/api/rutafv/quote',auth,async(req,res)=>{try{const d=read();const u=d.users.find(x=>x.id===req.user.id)||{};const c=req.body.customer||{};const customer={name:String(c.name||u.name||''),email:String(c.email||u.email||req.user.email||''),phone:String(c.phone||req.body.phone||'')};const destination={address:String(c.address||req.body.address||''),city:String(c.city||req.body.city||''),postalCode:String(c.postalCode||req.body.postalCode||''),notes:String(c.notes||req.body.notes||'')};if(!customer.name||!customer.email||!customer.phone||!destination.address||!destination.city||!destination.postalCode)return res.status(400).json({error:'Faltan datos del cliente o de entrega'});const items=[];for(const x of req.body.items||[]){const p=d.products.find(y=>y.id===x.id);if(p)items.push({ref:p.ref,title:p.title,qty:Math.max(1,Number(x.qty)||1),weightKg:Number(p.weightKg||0),sourceProvider:p.sourceProvider||'',sourceUrl:p.sourceUrl||''})}const payload={clientCode:RUTAFV_CLIENT_CODE,customer,destination,destinationText:[destination.address,destination.city,destination.postalCode].filter(Boolean).join(', '),items,orderSource:'FVMarket'};const q=await rutaFVRequest(RUTAFV_QUOTE_PATH,payload);res.json(q)}catch(e){res.status(503).json({error:e.name==='TimeoutError'?'RutaFV no respondió dentro del tiempo esperado':e.message})}});"""
if oldroute not in t: raise SystemExit('rutafv quote route not found')
t=t.replace(oldroute,newroute)
# enrich order record with customer details without breaking legacy consumers
t=t.replace("const {items,address,phone,paymentMethod='transfer'}=req.body||{};", "const {items,address,phone,paymentMethod='transfer'}=req.body||{};const customer=req.body.customer||{};")
t=t.replace("total,address:String(address||''),phone:String(phone||''),paymentMethod", "total,customer:{name:String(customer.name||''),email:String(customer.email||req.user.email||''),phone:String(customer.phone||phone||''),address:String(customer.address||address||''),city:String(customer.city||req.body.city||''),postalCode:String(customer.postalCode||req.body.postalCode||''),notes:String(customer.notes||req.body.notes||'')},address:String(customer.address||address||''),city:String(customer.city||req.body.city||''),postalCode:String(customer.postalCode||req.body.postalCode||''),notes:String(customer.notes||req.body.notes||''),phone:String(customer.phone||phone||''),paymentMethod")
t=t.replace("customer:{name:u.name||'',email:u.email||'',phone:o.phone||''},destination:o.address", "customer:{name:o.customer?.name||u.name||'',email:o.customer?.email||u.email||'',phone:o.customer?.phone||o.phone||''},destination:{address:o.customer?.address||o.address||'',city:o.customer?.city||o.city||'',postalCode:o.customer?.postalCode||o.postalCode||'',notes:o.customer?.notes||o.notes||''},destinationText:[o.customer?.address||o.address,o.customer?.city||o.city,o.customer?.postalCode||o.postalCode].filter(Boolean).join(', ')")
srv.write_text(t,encoding='utf-8')
print('OK customer + RutaFV checkout patch')
