const axios=require('axios');
const cheerio=require('cheerio');

const PROVIDERS={
  mandatelo:{key:'mandatelo',name:'Mandatelo',base:'https://mandatelo.com',hosts:['mandatelo.com','www.mandatelo.com'],search:q=>[
    `https://mandatelo.com/busqueda?controller=search&s=${encodeURIComponent(q)}`,
    `https://mandatelo.com/search?controller=search&s=${encodeURIComponent(q)}`,
    `https://mandatelo.com/?s=${encodeURIComponent(q)}`
  ],productRx:/mandatelo\.com\/(?!1256-ferreteria|busqueda|search|proximamente)(?:[^?#]+)(?:\.html)?(?:[?#]|$)/i},
  obramat:{key:'obramat',name:'Obramat',base:'https://www.obramat.es',hosts:['obramat.es','www.obramat.es'],store:'Jinámar',search:q=>[
    `https://www.obramat.es/buscador?q=${encodeURIComponent(q)}`,
    `https://www.obramat.es/search?q=${encodeURIComponent(q)}`,
    `https://www.obramat.es/search/?text=${encodeURIComponent(q)}`
  ],productRx:/obramat\.es\/productos\/[^?#]+-\d+\.html/i},
  leroy:{key:'leroy',name:'Leroy Merlin',base:'https://www.leroymerlin.es',hosts:['leroymerlin.es','www.leroymerlin.es'],search:q=>[
    `https://www.leroymerlin.es/buscador?q=${encodeURIComponent(q)}`,
    `https://www.leroymerlin.es/search?q=${encodeURIComponent(q)}`,
    `https://www.leroymerlin.es/productos/?q=${encodeURIComponent(q)}`
  ],productRx:/leroymerlin\.es\/productos\/[^?#]+-\d+\.html/i}
};

const headers=()=>({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','Accept-Language':'es-ES,es;q=0.9,en;q=0.7','Accept':'text/html,application/xhtml+xml'});
function abs(v,base){try{return new URL(String(v||''),base).href}catch{return''}}
function sameHost(url,cfg){try{return cfg.hosts.includes(new URL(url).hostname.toLowerCase())}catch{return false}}
function compact(s=''){return String(s).replace(/\s+/g,' ').trim()}
function money(v){if(v==null)return 0;let s=String(v).replace(/[^0-9,.-]/g,'').trim();if(!s)return 0;if(s.includes(',')&&s.includes('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function walkProduct(v){if(!v)return null;if(Array.isArray(v)){for(const x of v){const r=walkProduct(x);if(r)return r}return null}if(typeof v!=='object')return null;const t=v['@type'];if((Array.isArray(t)?t: [t]).filter(Boolean).some(x=>String(x).toLowerCase()==='product'))return v;for(const k of ['@graph','mainEntity','itemListElement']){const r=walkProduct(v[k]);if(r)return r}return null}
function productLd($){let out=null;$('script[type="application/ld+json"]').each((_,el)=>{if(out)return;try{out=walkProduct(JSON.parse($(el).html()||'null'))}catch{}});return out||{}}
function collectImages($,prod,url){const arr=[];const push=v=>{const u=abs(typeof v==='string'?v:(v?.url||v?.contentUrl||''),url);if(!u||!/^https?:/i.test(u)||/logo|icon|sprite|favicon|payment|badge/i.test(u))return;if(!arr.includes(u))arr.push(u)};const imgs=Array.isArray(prod?.image)?prod.image:[prod?.image];imgs.filter(Boolean).forEach(push);push($('meta[property="og:image"]').attr('content'));$('img').each((_,el)=>{const e=$(el);push(e.attr('data-zoom-image')||e.attr('data-large')||e.attr('data-src')||e.attr('src'))});return arr.slice(0,6)}
async function get(url){return axios.get(url,{timeout:22000,maxRedirects:5,headers:headers()})}
function productLinkFromSearch(html,ref,searchUrl,cfg){const $=cheerio.load(html);const target=String(ref||'').toUpperCase();let best='';let fallback='';$('a[href]').each((_,el)=>{const href=abs($(el).attr('href'),searchUrl);if(!href||!sameHost(href,cfg)||!cfg.productRx.test(href))return;const text=compact($(el).text()).toUpperCase();const h=href.toUpperCase();if(!fallback)fallback=href;if(target&&(text.includes(target)||h.includes(target)))best=href});return best||fallback}
async function resolveInput(cfg,input){const raw=compact(input);if(!raw)throw new Error('Introduce una referencia o URL');if(/^https?:\/\//i.test(raw)){if(!sameHost(raw,cfg))throw new Error(`La URL debe pertenecer a ${cfg.name}`);return raw}const ref=raw.replace(/\s+/g,'');for(const u of cfg.search(ref)){try{const r=await get(u);const found=productLinkFromSearch(r.data,ref,u,cfg);if(found)return found}catch{}}throw new Error(`No se encontró la referencia ${ref} en ${cfg.name}. Prueba pegando la URL exacta de la ficha.`)}
function parseFacts(cfg,html,url){const $=cheerio.load(html);const prod=productLd($);const body=compact($('body').text());const title=compact(prod.name||$('h1').first().text()||$('meta[property="og:title"]').attr('content')||$('title').text()).slice(0,180);let price=money(prod?.offers?.price||prod?.offers?.lowPrice||$('meta[property="product:price:amount"]').attr('content')||$('[itemprop="price"]').first().attr('content')||$('[itemprop="price"]').first().text());if(!price){const m=body.match(/(?:^|\s)(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|EUR)\b/i);if(m)price=money(m[1])}
  let ref='';if(cfg.key==='mandatelo'){ref=compact((body.match(/\bREF\s*:\s*([A-Z0-9._-]+)/i)||[])[1]||prod.sku||prod.mpn||'')}else{ref=compact((body.match(/\bRef\.\s*([A-Z0-9._-]+)/i)||[])[1]||prod.sku||prod.mpn||'')}
  if(!ref){const m=url.match(/-(\d{6,10})\.html(?:[?#]|$)/i);if(m)ref=m[1]}
  const ean=compact(prod.gtin13||prod.gtin||prod.gtin12||((body.match(/\b(\d{13})\b/)||[])[1]||''));const brand=compact(typeof prod.brand==='string'?prod.brand:(prod.brand?.name||''));const description=compact(prod.description||$('meta[name="description"]').attr('content')||'').slice(0,1000);let availability='';if(/No disponible/i.test(body))availability='No disponible';else if(/Disponible|En stock|Quedan \d+/i.test(body))availability='Disponible';else availability='Consultar disponibilidad';let seller='';if(cfg.key==='leroy'){const sm=body.match(/Vendido(?:\s+y enviado)? por\s+(.{2,80}?)(?=\s{2,}|Quedan|Entrega|Cantidad|Añadir|$)/i);seller=compact(sm?.[1]||prod?.offers?.seller?.name||'')}
  return {sourceTitle:title,sourceDescription:description,sourcePrice:price,sourceRef:ref.toUpperCase(),sourceEan:ean,sourceBrand:brand,sourceAvailability:availability,sourceTaxNote:cfg.key==='obramat'?'Precio mostrado por Obramat; disponibilidad del almacén Jinámar debe confirmarse en la ficha.':'',sourceStore:cfg.store||'',sourceSeller:seller,sourceUrl:url,sourceImages:collectImages($,prod,url)}
}
function fallbackOwn(deps,f){const title=deps.cleanProductTitle(f.sourceTitle||('Producto '+f.sourceRef));const category=deps.guessCategory(title+' '+f.sourceDescription);return {title,category,description:`Producto de ${String(category||'Otros').toLowerCase()} disponible bajo pedido en FVMarket. Ficha comercial preparada para revisión antes de publicar.`}}
async function analyzeOne(cfg,input,margin,deps,previewData){const url=await resolveInput(cfg,input);const r=await get(url);const f=parseFacts(cfg,r.data,url);if(!f.sourceTitle)throw new Error('No se pudo identificar el nombre del producto');if(!f.sourcePrice)throw new Error('No se pudo identificar el precio del producto');if(!f.sourceRef)f.sourceRef=compact(input).toUpperCase();let own=fallbackOwn(deps,f);try{const ai=await deps.aiAnalyzeItems([{title:f.sourceTitle,description:f.sourceDescription,sourcePrice:f.sourcePrice,sourceRef:f.sourceRef}]);if(ai?.products?.[0]){const p=ai.products[0];own={title:deps.cleanProductTitle(p.title||own.title),category:p.category||own.category,description:compact(p.description||own.description).slice(0,700)}}}catch{}
  const m=Math.max(0,Math.min(300,Number(margin)||40));const addedValue=+(f.sourcePrice*m/100).toFixed(2);const price=+(f.sourcePrice+addedValue).toFixed(2);const ref=deps.nextProductRef(previewData,own.title,own.category);previewData.products=previewData.products||[];previewData.products.unshift({ref});return {...own,ref,providerKey:cfg.key,sourceProvider:cfg.name,sourceRef:f.sourceRef,sourceEan:f.sourceEan,sourceBrand:f.sourceBrand,sourceAvailability:f.sourceAvailability,sourceTaxNote:f.sourceTaxNote,sourceStore:f.sourceStore,sourceSeller:f.sourceSeller,sourceUrl:f.sourceUrl,sourceImages:f.sourceImages,sourcePrice:f.sourcePrice,margin:m,addedValue,price,stock:'bajo_pedido',published:false,featured:false,image:'',images:[],reviewStatus:'borrador'}
}

function registerProviderSourceRoutes(app,admin,deps){
  app.post('/api/admin/provider/:provider/analyze',admin,async(req,res)=>{const cfg=PROVIDERS[String(req.params.provider||'').toLowerCase()];if(!cfg)return res.status(404).json({error:'Proveedor no configurado'});const inputs=Array.isArray(req.body.inputs)?req.body.inputs.slice(0,30):[];if(!inputs.length)return res.status(400).json({error:'Introduce al menos una referencia o URL'});const previewData=deps.read();const products=[],errors=[];for(const input of inputs){try{products.push(await analyzeOne(cfg,input,req.body.margin,deps,previewData))}catch(e){errors.push({input,error:String(e.message||e)})}}res.json({provider:cfg.name,products,errors})});
  app.post('/api/admin/provider/import',admin,(req,res)=>{const items=Array.isArray(req.body.products)?req.body.products.slice(0,50):[];if(!items.length)return res.status(400).json({error:'No hay productos seleccionados'});const d=deps.read();let created=0,skipped=0;const products=[];for(const x of items){const sourceProvider=compact(x.sourceProvider||'Proveedor');const sourceRef=compact(x.sourceRef).toUpperCase();if(!sourceRef||d.products.some(p=>compact(p.sourceProvider).toLowerCase()===sourceProvider.toLowerCase()&&compact(p.sourceRef).toUpperCase()===sourceRef)){skipped++;continue}const title=deps.cleanProductTitle(x.title||('Producto '+sourceRef));const category=String(x.category||deps.guessCategory(title));const sourcePrice=Number(x.sourcePrice)||0;if(!sourcePrice){skipped++;continue}const margin=Math.max(0,Math.min(300,Number(x.margin)||40));const addedValue=+(sourcePrice*margin/100).toFixed(2);const price=+(sourcePrice+addedValue).toFixed(2);const images=deps.normalizeProductImages(Array.isArray(x.images)?x.images:[]).filter(im=>String(im.origin||'')==='free-prep'||String(im.origin||'')==='ai-render'||/^data:image\//i.test(String(im.url||''))).slice(0,6);if(images.length<1){skipped++;continue}const ref=deps.nextProductRef(d,title,category);const p={id:deps.id('prd'),title,category,subcategory:String(x.subcategory||''),ref,price,stock:'bajo_pedido',image:images[0]?.url||'',images,imageSource:images.some(im=>im.origin==='ai-render')?'IA FVMarket':'Preparación FVMarket',imageLicense:'',imageAuthor:'',description:String(x.description||'').slice(0,900),published:false,featured:false,onOffer:false,discountPct:0,providerKey:String(x.providerKey||''),sourceProvider,sourceRef,sourceEan:String(x.sourceEan||''),sourceBrand:String(x.sourceBrand||''),sourceAvailability:String(x.sourceAvailability||''),sourceTaxNote:String(x.sourceTaxNote||''),sourceStore:String(x.sourceStore||''),sourceSeller:String(x.sourceSeller||''),sourceUrl:String(x.sourceUrl||''),sourceImages:Array.isArray(x.sourceImages)?x.sourceImages.slice(0,6):[],sourcePrice,margin,addedValue,sourceCheckedAt:new Date().toISOString(),sourceSync:'provider_v11',reviewStatus:'borrador',importedAt:new Date().toISOString()};d.products.unshift(p);products.push(p);created++}deps.save(d);res.json({created,skipped,products})});
}
module.exports={registerProviderSourceRoutes};
