const axios=require('axios');
const cheerio=require('cheerio');

const GOOGLE_CSE_API_KEY=String(process.env.GOOGLE_CSE_API_KEY||'').trim();
const GOOGLE_CSE_CX=String(process.env.GOOGLE_CSE_CX||'').trim();
const BRAVE_SEARCH_API_KEY=String(process.env.BRAVE_SEARCH_API_KEY||'').trim();
console.log('[provider-v12] search fallback: '+((GOOGLE_CSE_API_KEY&&GOOGLE_CSE_CX)?'google-cse':(BRAVE_SEARCH_API_KEY?'brave':'none')));

const PROVIDERS={
  mibricolaje:{key:'mibricolaje',name:'MiBricolaje',base:'https://mibricolaje.com',domain:'mibricolaje.com',hosts:['mibricolaje.com','www.mibricolaje.com'],search:q=>[
    `https://mibricolaje.com/buscar?controller=search&s=${encodeURIComponent(q)}`,
    `https://mibricolaje.com/search?controller=search&s=${encodeURIComponent(q)}`,
    `https://mibricolaje.com/?s=${encodeURIComponent(q)}`
  ],productRx:/mibricolaje\.com\/(?!buscar|search|img\/cms)(?:[^?#]+\.html)(?:[?#]|$)/i},
  mandatelo:{key:'mandatelo',name:'Mandatelo',base:'https://mandatelo.com',domain:'mandatelo.com',hosts:['mandatelo.com','www.mandatelo.com'],search:q=>[
    `https://mandatelo.com/busqueda?controller=search&s=${encodeURIComponent(q)}`,
    `https://mandatelo.com/search?controller=search&s=${encodeURIComponent(q)}`,
    `https://mandatelo.com/?s=${encodeURIComponent(q)}`
  ],productRx:/mandatelo\.com\/(?!1256-ferreteria|busqueda|search|proximamente)(?:[^?#]+)(?:\.html)?(?:[?#]|$)/i},
  obramat:{key:'obramat',name:'Obramat',base:'https://www.obramat.es',domain:'obramat.es',hosts:['obramat.es','www.obramat.es'],store:'Jinámar',search:q=>[
    `https://www.obramat.es/search?q=${encodeURIComponent(q)}`,
    `https://www.obramat.es/buscador?q=${encodeURIComponent(q)}`
  ],productRx:/obramat\.es\/productos\/[^?#]+-\d+\.html/i},
  leroy:{key:'leroy',name:'Leroy Merlin',base:'https://www.leroymerlin.es',domain:'leroymerlin.es',hosts:['leroymerlin.es','www.leroymerlin.es'],store:'Telde',search:q=>[
    `https://www.leroymerlin.es/buscador?q=${encodeURIComponent(q)}`,
    `https://www.leroymerlin.es/search?q=${encodeURIComponent(q)}`,
    `https://www.leroymerlin.es/productos/?q=${encodeURIComponent(q)}`
  ],productRx:/leroymerlin\.es\/productos\/[^?#]+-\d+\.html/i}
};

const headers=()=>({'User-Agent':'FVMarket/2.2 (+admin-assisted product lookup)','Accept-Language':'es-ES,es;q=0.9,en;q=0.6','Accept':'text/html,application/xhtml+xml','Cache-Control':'no-cache'});
function abs(v,base){try{return new URL(String(v||''),base).href}catch{return''}}
function sameHost(url,cfg){try{return cfg.hosts.includes(new URL(url).hostname.toLowerCase())}catch{return false}}
function compact(s=''){return String(s).replace(/\s+/g,' ').trim()}
function cleanRef(v=''){return compact(v).toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9._-]/g,'').slice(0,40)}
function validRef(v=''){return /^[A-Z0-9][A-Z0-9._-]{2,39}$/i.test(cleanRef(v))}
function money(v){if(v==null)return 0;let s=String(v).replace(/[^0-9,.-]/g,'').trim();if(!s)return 0;if(s.includes(',')&&s.includes('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)&&n>0?n:0}
function priceFromText(text=''){const s=compact(text);const patterns=[/(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|EUR)/i,/(?:€|EUR)\s*(\d{1,5}(?:[.,]\d{1,2})?)/i];for(const rx of patterns){const m=s.match(rx);if(m){const n=money(m[1]);if(n)return n}}return 0}
function walkProduct(v){if(!v)return null;if(Array.isArray(v)){for(const x of v){const r=walkProduct(x);if(r)return r}return null}if(typeof v!=='object')return null;const t=v['@type'];if((Array.isArray(t)?t:[t]).filter(Boolean).some(x=>String(x).toLowerCase()==='product'))return v;for(const k of ['@graph','mainEntity','itemListElement']){const r=walkProduct(v[k]);if(r)return r}return null}
function productLd($){let out=null;$('script[type="application/ld+json"]').each((_,el)=>{if(out)return;try{out=walkProduct(JSON.parse($(el).html()||'null'))}catch{}});return out||{}}
function collectImages($,prod,url){const arr=[];const push=v=>{const u=abs(typeof v==='string'?v:(v?.url||v?.contentUrl||''),url);if(!u||!/^https?:/i.test(u)||/logo|icon|sprite|favicon|payment|badge/i.test(u))return;if(!arr.includes(u))arr.push(u)};const imgs=Array.isArray(prod?.image)?prod.image:[prod?.image];imgs.filter(Boolean).forEach(push);push($('meta[property="og:image"]').attr('content'));push($('link[rel="image_src"]').attr('href'));$('img').each((_,el)=>{const e=$(el);push(e.attr('data-zoom-image')||e.attr('data-large')||e.attr('data-src')||e.attr('src'))});return arr.slice(0,8)}
async function get(url){return axios.get(url,{timeout:22000,maxRedirects:5,maxContentLength:5*1024*1024,headers:headers()})}
function refFromUrl(url=''){const m=String(url).match(/-([A-Z0-9]{4,20})\.html(?:[?#]|$)/i);return cleanRef(m?.[1]||'')}
function productLinkFromSearch(html,ref,searchUrl,cfg){const $=cheerio.load(html);const target=cleanRef(ref);let exact='';let fallback='';$('a[href]').each((_,el)=>{const href=abs($(el).attr('href'),searchUrl);if(!href||!sameHost(href,cfg)||!cfg.productRx.test(href))return;const text=compact($(el).text()).toUpperCase();const h=href.toUpperCase();if(!fallback)fallback=href;if(target&&(text.includes(target)||h.includes(target)))exact=href});return exact||fallback}

function googlePagemapFacts(item={},cfg,requestedRef=''){
  const pm=item.pagemap||{};const metas=Array.isArray(pm.metatags)?pm.metatags[0]||{}:{};const products=Array.isArray(pm.product)?pm.product:[];const offers=Array.isArray(pm.offer)?pm.offer:[];const p=products[0]||{};const o=offers[0]||{};
  const title=compact(p.name||item.title||metas['og:title']||'').replace(/\s*[|·-]\s*(?:Leroy Merlin|Obramat|MiBricolaje|Mandatelo).*$/i,'').slice(0,180);
  let price=money(o.price||p.price||metas['product:price:amount']||metas['og:price:amount']||metas['twitter:data1']);if(!price)price=priceFromText(item.snippet||'');
  const images=[];const push=u=>{u=String(u||'');if(/^https?:/i.test(u)&&!images.includes(u))images.push(u)};(pm.cse_image||[]).forEach(x=>push(x.src));push(p.image);push(metas['og:image']);
  return {sourceTitle:title,sourceDescription:compact(item.snippet||metas.description||metas['og:description']||'').slice(0,1000),sourcePrice:price,sourceRef:cleanRef(p.sku||metas['product:retailer_item_id']||requestedRef||refFromUrl(item.link)),sourceEan:cleanRef(p.gtin13||p.gtin||''),sourceBrand:compact(p.brand||''),sourceAvailability:compact(o.availability||metas['product:availability']||'')||'Consultar disponibilidad',sourceUrl:item.link||'',sourceImages:images.slice(0,6),sourceSeller:'',sourceStore:cfg.store||'',sourceTaxNote:''}
}
async function googleSearch(cfg,query){if(!GOOGLE_CSE_API_KEY||!GOOGLE_CSE_CX)return null;try{const r=await axios.get('https://www.googleapis.com/customsearch/v1',{timeout:15000,params:{key:GOOGLE_CSE_API_KEY,cx:GOOGLE_CSE_CX,q:`site:${cfg.domain} ${query}`,num:10}});return r.data||null}catch{return null}}
async function braveWeb(cfg,query){if(!BRAVE_SEARCH_API_KEY)return null;try{const r=await axios.get('https://api.search.brave.com/res/v1/web/search',{timeout:15000,params:{q:`site:${cfg.domain} ${query}`,count:10,country:'es',search_lang:'es'},headers:{Accept:'application/json','X-Subscription-Token':BRAVE_SEARCH_API_KEY}});return r.data||null}catch{return null}}
async function braveImages(cfg,query){if(!BRAVE_SEARCH_API_KEY)return[];try{const r=await axios.get('https://api.search.brave.com/res/v1/images/search',{timeout:15000,params:{q:`site:${cfg.domain} ${query}`,count:8,country:'es',search_lang:'es'},headers:{Accept:'application/json','X-Subscription-Token':BRAVE_SEARCH_API_KEY}});const a=r.data?.results||[];return a.map(x=>x?.properties?.url||x?.thumbnail?.src||x?.url||'').filter(u=>/^https?:/i.test(u)).slice(0,6)}catch{return[]}}
function pickGoogleItem(data,cfg,query){const target=cleanRef(query);const items=data?.items||[];return items.find(x=>sameHost(x.link,cfg)&&target&&(String(x.link).toUpperCase().includes(target)||String(x.title).toUpperCase().includes(target)||String(x.snippet).toUpperCase().includes(target)))||items.find(x=>sameHost(x.link,cfg)&&cfg.productRx.test(x.link))||null}
function pickBraveItem(data,cfg,query){const target=cleanRef(query);const items=data?.web?.results||[];return items.find(x=>sameHost(x.url,cfg)&&target&&(String(x.url).toUpperCase().includes(target)||String(x.title).toUpperCase().includes(target)||String(x.description).toUpperCase().includes(target)))||items.find(x=>sameHost(x.url,cfg)&&cfg.productRx.test(x.url))||null}
async function indexedFacts(cfg,query,preferredUrl=''){
  const g=await googleSearch(cfg,query);const gi=pickGoogleItem(g,cfg,query);if(gi){const f=googlePagemapFacts(gi,cfg,query);if(preferredUrl&&sameHost(preferredUrl,cfg))f.sourceUrl=preferredUrl;if(!f.sourceImages.length)f.sourceImages=await braveImages(cfg,`${query} ${f.sourceTitle}`);return f}
  const b=await braveWeb(cfg,query);const bi=pickBraveItem(b,cfg,query);if(bi){const sourceUrl=(preferredUrl&&sameHost(preferredUrl,cfg))?preferredUrl:bi.url;const images=await braveImages(cfg,`${query} ${bi.title||''}`);return {sourceTitle:compact(bi.title||'').replace(/\s*[|·-]\s*(?:Leroy Merlin|Obramat|MiBricolaje|Mandatelo).*$/i,'').slice(0,180),sourceDescription:compact(bi.description||'').slice(0,1000),sourcePrice:priceFromText(bi.description||bi.title||''),sourceRef:cleanRef(query||refFromUrl(sourceUrl)),sourceEan:'',sourceBrand:'',sourceAvailability:'Consultar disponibilidad',sourceUrl,sourceImages:images,sourceSeller:'',sourceStore:cfg.store||'',sourceTaxNote:''}
  }
  return null
}

async function resolveInput(cfg,input){const raw=compact(input);if(!raw)throw new Error('Introduce una referencia o URL');if(/^https?:\/\//i.test(raw)){if(!sameHost(raw,cfg))throw new Error(`La URL debe pertenecer a ${cfg.name}`);return {url:raw,requestedRef:refFromUrl(raw),raw}}
  const ref=cleanRef(raw);if(!validRef(ref))throw new Error('Referencia no válida');for(const u of cfg.search(ref)){try{const r=await get(u);const found=productLinkFromSearch(r.data,ref,u,cfg);if(found)return {url:found,requestedRef:ref,raw}}catch{}}
  const idx=await indexedFacts(cfg,ref);if(idx?.sourceUrl)return {url:idx.sourceUrl,requestedRef:ref,raw,indexed:idx};throw new Error(`No se encontró la referencia ${ref} en ${cfg.name}.`)}

function parseFacts(cfg,html,url,requestedRef=''){const $=cheerio.load(html);const prod=productLd($);const offers=Array.isArray(prod.offers)?prod.offers[0]:(prod.offers||{});const body=compact($('body').text());const title=compact(prod.name||$('h1').first().text()||$('meta[property="og:title"]').attr('content')||$('title').text()).slice(0,180);let price=money(offers?.price||offers?.lowPrice||$('meta[property="product:price:amount"]').attr('content')||$('meta[property="og:price:amount"]').attr('content')||$('[itemprop="price"]').first().attr('content')||$('[itemprop="price"]').first().text()||$('[data-price]').first().attr('data-price'));if(!price)price=priceFromText(body);
  let ref='';if(cfg.key==='mandatelo')ref=cleanRef((body.match(/\bREF\s*:\s*([A-Z0-9._-]+)/i)||[])[1]||prod.sku||prod.mpn||requestedRef);else if(cfg.key==='mibricolaje')ref=cleanRef((body.match(/\bReferencia\s*:\s*([A-Z0-9._-]+)/i)||[])[1]||prod.sku||prod.mpn||requestedRef);else ref=cleanRef((body.match(/\bRef\.?\s*[:]?\s*([A-Z0-9._-]+)/i)||[])[1]||prod.sku||prod.mpn||requestedRef||refFromUrl(url));
  const ean=compact(prod.gtin13||prod.gtin||prod.gtin12||((body.match(/\b(?:EAN\s*:\s*)?(\d{13})\b/i)||[])[1]||''));const brand=compact(typeof prod.brand==='string'?prod.brand:(prod.brand?.name||''));const description=compact(prod.description||$('meta[name="description"]').attr('content')||'').slice(0,1000);let availability='Consultar disponibilidad';if(/Fuera de stock|No disponible|Agotado/i.test(body))availability='No disponible';else if(/Disponible|En stock|Quedan \d+/i.test(body))availability='Disponible';let seller='';if(cfg.key==='leroy'){const sm=body.match(/Vendido(?:\s+y enviado)? por\s+([A-ZÁÉÍÓÚÜÑ0-9 .&_-]{2,80})/i);seller=compact(sm?.[1]||offers?.seller?.name||'')}
  const note=cfg.key==='obramat'?`Precio de ficha pública; disponibilidad en Obramat ${cfg.store} debe confirmarse.`:cfg.key==='leroy'?`Precio de ficha pública; disponibilidad en Leroy Merlin ${cfg.store} debe confirmarse.`:'';
  return {sourceTitle:title,sourceDescription:description,sourcePrice:price,sourceRef:ref,sourceEan:ean,sourceBrand:brand,sourceAvailability:availability,sourceTaxNote:note,sourceStore:cfg.store||'',sourceSeller:seller,sourceUrl:url,sourceImages:collectImages($,prod,url)}
}
function fallbackOwn(deps,f){const title=deps.cleanProductTitle(f.sourceTitle||('Producto '+f.sourceRef));const category=deps.guessCategory(title+' '+f.sourceDescription);return {title,category,description:`Producto de ${String(category||'Otros').toLowerCase()} disponible bajo pedido en FVMarket. Ficha comercial preparada para revisión antes de publicar.`}}
async function analyzeOne(cfg,input,margin,deps,previewData){const resolved=await resolveInput(cfg,input);let f=resolved.indexed||null;let directError=null;if(!f||!f.sourcePrice||!f.sourceTitle||!f.sourceImages?.length){try{const r=await get(resolved.url);f=parseFacts(cfg,r.data,resolved.url,resolved.requestedRef)}catch(e){directError=e}}
  if((!f||!f.sourcePrice||!f.sourceTitle)&&resolved.requestedRef){const idx=await indexedFacts(cfg,resolved.requestedRef,resolved.url);if(idx)f={...(f||{}),...idx,sourceImages:(f?.sourceImages?.length?f.sourceImages:idx.sourceImages)}}
  if(!f)throw new Error(directError?.response?.status===403?'La tienda bloqueó la lectura automática y no hubo datos públicos suficientes de respaldo.':'No se pudo leer la ficha del producto.');
  if(!f.sourceTitle)throw new Error('No se pudo identificar el nombre del producto');if(!f.sourcePrice)throw new Error('No se pudo identificar el precio actual del producto');if(!f.sourceRef)f.sourceRef=resolved.requestedRef||cleanRef(input);if(resolved.requestedRef&&cleanRef(f.sourceRef)!==cleanRef(resolved.requestedRef))throw new Error(`La ficha encontrada corresponde a ${f.sourceRef}, no a ${resolved.requestedRef}`);
  if(cfg.key==='obramat'){f.sourceStore='Jinámar';f.sourceTaxNote='Precio de la ficha pública. Stock/disponibilidad debe confirmarse para Obramat Jinámar.'}if(cfg.key==='leroy'){f.sourceStore='Telde';f.sourceTaxNote='Precio de la ficha pública. Stock/disponibilidad debe confirmarse para Leroy Merlin Telde.'}
  let own=fallbackOwn(deps,f);try{const ai=await deps.aiAnalyzeItems([{title:f.sourceTitle,description:f.sourceDescription,sourcePrice:f.sourcePrice,sourceRef:f.sourceRef}]);if(ai?.products?.[0]){const p=ai.products[0];own={title:deps.cleanProductTitle(p.title||own.title),category:p.category||own.category,description:compact(p.description||own.description).slice(0,700)}}}catch{}
  const m=Math.max(0,Math.min(300,Number(margin)||40));const addedValue=+(f.sourcePrice*m/100).toFixed(2);const price=+(f.sourcePrice+addedValue).toFixed(2);const ref=deps.nextProductRef(previewData,own.title,own.category);previewData.products=previewData.products||[];previewData.products.unshift({ref});return {...own,ref,providerKey:cfg.key,sourceProvider:cfg.name,sourceRef:f.sourceRef,sourceEan:f.sourceEan||'',sourceBrand:f.sourceBrand||'',sourceAvailability:f.sourceAvailability||'Consultar disponibilidad',sourceTaxNote:f.sourceTaxNote||'',sourceStore:f.sourceStore||cfg.store||'',sourceSeller:f.sourceSeller||'',sourceUrl:f.sourceUrl||resolved.url,sourceImages:f.sourceImages||[],sourcePrice:f.sourcePrice,sourceCheckedAt:new Date().toISOString(),margin:m,addedValue,price,stock:'bajo_pedido',published:false,featured:false,image:'',images:[],reviewStatus:'borrador'}
}

function registerProviderSourceRoutes(app,admin,deps){
  app.post('/api/admin/provider/:provider/analyze',admin,async(req,res)=>{const cfg=PROVIDERS[String(req.params.provider||'').toLowerCase()];if(!cfg)return res.status(404).json({error:'Proveedor no configurado'});const inputs=Array.isArray(req.body.inputs)?req.body.inputs.slice(0,30):[];if(!inputs.length)return res.status(400).json({error:'Introduce al menos una referencia o URL'});const previewData=deps.read();const products=[],errors=[];for(const input of inputs){try{products.push(await analyzeOne(cfg,input,req.body.margin,deps,previewData))}catch(e){errors.push({input,error:String(e.message||e)})}}res.json({provider:cfg.name,store:cfg.store||'',products,errors})});
  app.post('/api/admin/provider/import',admin,(req,res)=>{const items=Array.isArray(req.body.products)?req.body.products.slice(0,50):[];if(!items.length)return res.status(400).json({error:'No hay productos seleccionados'});const d=deps.read();let created=0,skipped=0;const products=[];for(const x of items){const sourceProvider=compact(x.sourceProvider||'Proveedor');const sourceRef=cleanRef(x.sourceRef);if(!sourceRef||d.products.some(p=>compact(p.sourceProvider).toLowerCase()===sourceProvider.toLowerCase()&&cleanRef(p.sourceRef)===sourceRef)){skipped++;continue}const title=deps.cleanProductTitle(x.title||('Producto '+sourceRef));const category=String(x.category||deps.guessCategory(title));const sourcePrice=Number(x.sourcePrice)||0;if(!sourcePrice){skipped++;continue}const margin=Math.max(0,Math.min(300,Number(x.margin)||40));const addedValue=+(sourcePrice*margin/100).toFixed(2);const price=+(sourcePrice+addedValue).toFixed(2);const images=deps.normalizeProductImages(Array.isArray(x.images)?x.images:[]).filter(im=>String(im.origin||'').startsWith('free-prep')||String(im.origin||'')==='ai-render'||/^data:image\//i.test(String(im.url||''))).slice(0,6);if(images.length<1){skipped++;continue}const ref=deps.nextProductRef(d,title,category);const p={id:deps.id('prd'),title,category,subcategory:String(x.subcategory||''),ref,price,stock:'bajo_pedido',image:images[0]?.url||'',images,imageSource:images.some(im=>im.origin==='ai-render')?'IA FVMarket':'Preparación FVMarket',imageLicense:'',imageAuthor:'',description:String(x.description||'').slice(0,900),published:false,featured:false,onOffer:false,discountPct:0,providerKey:String(x.providerKey||''),sourceProvider,sourceRef,sourceEan:String(x.sourceEan||''),sourceBrand:String(x.sourceBrand||''),sourceAvailability:String(x.sourceAvailability||''),sourceTaxNote:String(x.sourceTaxNote||''),sourceStore:String(x.sourceStore||''),sourceSeller:String(x.sourceSeller||''),sourceUrl:String(x.sourceUrl||''),sourceImages:Array.isArray(x.sourceImages)?x.sourceImages.slice(0,8):[],sourcePrice,margin,addedValue,sourceCheckedAt:String(x.sourceCheckedAt||new Date().toISOString()),sourceSync:'provider_v12',reviewStatus:'borrador',importedAt:new Date().toISOString()};d.products.unshift(p);products.push(p);created++}deps.save(d);res.json({created,skipped,products})});
}
module.exports={registerProviderSourceRoutes,_test:{PROVIDERS,priceFromText,parseFacts,resolveInput,indexedFacts,get}};
