from pathlib import Path
import json,re

server=Path('appsrc/server.js')
admin=Path('appsrc/public/admin.html')
adminjs=Path('appsrc/public/fvmarket-admin-v13.js')
index=Path('appsrc/public/index.html')
home=Path('appsrc/public/fvmarket-home-v13.js')
pkg=Path('appsrc/package.json')

s=server.read_text(encoding='utf-8')
if "require('./persistent_store_v17')" not in s:
    s=s.replace("const {registerProviderSourceRoutes} = require('./supplier_capture_v13');", "const {registerProviderSourceRoutes} = require('./supplier_capture_v13');\nconst persistence = require('./persistent_store_v17');")
if 'persistence.config(DATA_FILE);' not in s:
    s=s.replace("const DATA_FILE = process.env.DATA_FILE || path.join(__dirname, 'data.json');", "const DATA_FILE = process.env.DATA_FILE || path.join(__dirname, 'data.json');\npersistence.config(DATA_FILE);")
s=s.replace("function save(d){fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2))}","function save(d){fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2));persistence.persist(d)}")

# Commercial copy: keep RutaFV integration internal but remove it from customer-facing text generated by server.
s=s.replace("Disponible bajo pedido con entrega en Fuerteventura mediante RutaFV.","Disponible bajo pedido. Lo enviamos a tu obra en Fuerteventura.")
s=s.replace("name:'Transporte RutaFV',description:'Servicio de entrega asociado a la compra FVMarket'","name:'Envío a tu obra',description:'Servicio de entrega asociado a la compra FVMarket'")

# European image results are allowed: remove the former Spain exclusion.
s=s.replace(".filter(x=>x.url&&!isSpanishImageDomain(x.url)&&!isSpanishImageDomain(x.source))",".filter(x=>x.url)")
s=s.replace("if(!url||seen.has(url)||isSpanishImageDomain(url)||isSpanishImageDomain(src))continue;","if(!url||seen.has(url))continue;")
s=s.replace("+' · excluye dominios de España'","+' · búsqueda internacional y europea'")

# Bias ranking slightly toward European image sources without excluding the rest of the web.
needle="""  const full=[x.title,x.source,x.url].join(' ').toLowerCase();
  for(const t of qcrit)score+=full.includes(t)?6:-4;
  return score;"""
repl="""  const full=[x.title,x.source,x.url].join(' ').toLowerCase();
  for(const t of qcrit)score+=full.includes(t)?6:-4;
  try{const h=new URL(String(x.source||x.url||'')).hostname.toLowerCase();if(/\\.(?:es|fr|de|it|pt|nl|be|eu|at|ie|pl|cz|dk|se|fi|gr|ro|hu)$/.test(h))score+=2}catch{}
  return score;"""
if needle in s:s=s.replace(needle,repl,1)

# Similar-image search endpoint for supplier capture flow.
route="""
// FVM_SUPPLIER_SIMILAR_IMAGES_V17
app.post('/api/admin/suppliers/:id/search-images',admin,async(req,res)=>{
  const d=read();const supplier=(d.suppliers||[]).find(x=>x.id===req.params.id);
  if(!supplier)return res.status(404).json({error:'Proveedor no encontrado'});
  const title=String(req.body?.title||'').trim(),brand=String(req.body?.brand||'').trim(),sourceRef=String(req.body?.sourceRef||'').trim();
  const query=[sourceRef,brand,title].filter(Boolean).join(' ').slice(0,180);
  if(!query)return res.status(400).json({error:'Indica nombre o referencia para buscar imágenes'});
  try{const images=await searchExternalImages(query,Math.max(4,Math.min(12,Number(req.body?.limit)||12)));res.set('Cache-Control','no-store');res.json({query,images,includesEuropeanDomains:true})}
  catch(e){res.status(502).json({error:'No se pudo completar la búsqueda de imágenes: '+String(e.message||e)})}
});
app.get('/api/admin/persistence-status',admin,(req,res)=>res.json(persistence.status()));
"""
marker='// FVM_PROVIDER_ROUTES_V15 - API routes must be registered before the storefront catch-all.'
if 'FVM_SUPPLIER_SIMILAR_IMAGES_V17' not in s:
    if marker not in s:raise SystemExit('provider route marker missing')
    s=s.replace(marker,route+'\n'+marker,1)

# Start only after restoring persistent state.
old="app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));\napp.listen(PORT,'0.0.0.0',()=>console.log(`FVMarket listening on ${PORT}`));"
new="""app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
(async()=>{try{await persistence.init();read()}catch(e){console.error('FVMarket persistence bootstrap:',e)}app.listen(PORT,'0.0.0.0',()=>console.log(`FVMarket listening on ${PORT}`))})();"""
if old in s:s=s.replace(old,new,1)
elif 'persistence.init()' not in s:raise SystemExit('listen block missing')
server.write_text(s,encoding='utf-8')

# Expose supplier modal state so v17 tools can add selected web images to the actual product draft.
a=adminjs.read_text(encoding='utf-8')
state_line="const state={suppliers:[],taxonomy:{},selectedSupplier:null,products:[],capture:'',photos:[],editingSupplier:null};"
if 'window.fvmSupplierV13' not in a:
    if state_line not in a:raise SystemExit('supplier state missing')
    a=a.replace(state_line,state_line+"\n  window.fvmSupplierV13={state,renderPhotos:()=>renderPhotos()};",1)
# Remove the instructional 4-step cards from the generated supplier screen.
a=re.sub(r"\s*<div class=\"v13Flow\">.*?</div></div>\s*", "\n    ", a, count=1, flags=re.S)
adminjs.write_text(a,encoding='utf-8')

# Load new admin layer and remove the visible technical AI status block.
h=admin.read_text(encoding='utf-8')
if '/fvmarket-admin-v17.js' not in h:
    h=h.replace('<script src="/fvmarket-admin-crop-v16.js?v=16"></script>','<script src="/fvmarket-admin-crop-v16.js?v=16"></script>\n<script src="/fvmarket-admin-v17.js?v=17"></script>')
h=h.replace('<div id="aiState" class="aiState">Comprobando asistente inteligente...</div>','')
h=h.replace('<span class="pill">FVMarket + RutaFV</span>','<span class="pill">FVMarket</span>')
admin.write_text(h,encoding='utf-8')

# Storefront script and customer-facing copy.
i=index.read_text(encoding='utf-8')
i=i.replace('FVMarket: materiales y herramientas con entrega profesional en Fuerteventura mediante RutaFV.','FVMarket: materiales, herramientas y soluciones para tu proyecto. Lo enviamos a tu obra en Fuerteventura.')
replacements={
 'Transporte RutaFV':'Envío a tu obra',
 'RutaFV · Transporte':'Envío a tu obra',
 'Calculando transporte con RutaFV':'Calculando envío a tu obra',
 'Calcula primero el transporte RutaFV.':'Calcula primero el envío a tu obra.',
 'Entrega con RutaFV':'Lo enviamos a tu obra',
 'Entrega profesional con RutaFV':'Lo enviamos a tu obra',
}
for x,y in replacements.items():i=i.replace(x,y)
if '/fvmarket-storefront-v17.js' not in i:
    i=i.replace('<script src="/fvmarket-admin-entry-v14.js?v=14"></script>','<script src="/fvmarket-admin-entry-v14.js?v=14"></script>\n<script src="/fvmarket-storefront-v17.js?v=17"></script>')
index.write_text(i,encoding='utf-8')

hh=home.read_text(encoding='utf-8')
hh=hh.replace('Entrega profesional en toda Fuerteventura con <b>RutaFV</b>','<b>Lo enviamos a tu obra</b> en toda Fuerteventura')
hh=hh.replace('Entrega con <span>RutaFV</span>','Lo enviamos a tu obra')
hh=hh.replace('Entrega con RutaFV','Lo enviamos a tu obra')
home.write_text(hh,encoding='utf-8')

# PostgreSQL client for persistent state (uses DATABASE_URL/POSTGRES_URL when linked in Render).
p=json.loads(pkg.read_text(encoding='utf-8'))
p.setdefault('dependencies',{})['pg']='^8.13.1'
p['version']='1.7.0'
pkg.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

print('FVMarket v17 patch applied')
